### PR TITLE
`-' should be part of symbol

### PR DESCRIPTION
**Pull request by redguardtoo**
For example, consider,
- css class name like btn-default
- anglar directive like my-div
- attribute like data-on-change

Auto-completioin, code navigation need this feature

### CODE REVIEW

**Comment by stardiviner** [comment]
+1

**Comment by dgutov** [comment]
Keep in mind that this change makes `-` "part of word", not just "part of symbol".

**Comment by fxbois** [comment]
@dgutov would you suggest an other fix ? Have you identified issues ?

**Comment by dgutov** [comment]
> Have you identified issues?

I imagine `forward-word`, etc, don't work as expected. And it was already reported in https://github.com/fxbois/web-mode/issues/563.

**Comment by fxbois** [comment]
@dgutov what do you advice ? Remove the patch ? Adapt it ?

**Comment by dgutov** [comment]
I'd recommend

```lisp
(modify-syntax-entry ?_ "_" table)
(modify-syntax-entry ?- "_" table)
```

then you'll need to take care, apparently, of the "errors with the file demo.djhtml".

**Comment by fxbois** [comment]
@dgutov I've pushed your suggestion (I've solved the issues with demo.djhtml)

@redguardtoo is it still ok with you ?

**Comment by redguardtoo** [comment]
there is an issue for @dgutov code. the completion inside css class (for, example, `<div class="btn-default">`) doesn't work anymore.

**Comment by redguardtoo** [comment]
there is an issue for @dgutov code. the completion inside css class (for, example, `<div class="btn-default">`) doesn't work anymore. web-mode 13.0.3

**Comment by dgutov** [comment]
@redguardtoo "Doesn't work" how? But considering web-mode doesn't do completion, why would that be an issue here?

**Comment by redguardtoo** [comment]
@dgutov , I figure out what happened, it's actually company-mode's issue,  If you remove the line `(not (company-in-string-or-comment))`, company-etags works.

**Comment by dgutov** [comment]
What difference does the syntax class of `-` make?

**Comment by redguardtoo** [comment]
I think company-mode's issue instead of web-mode.  your web-mode code is fine.

**Comment by fxbois** [comment]
@dgutov could you look at my comment on the issue 
https://github.com/fxbois/web-mode/issues/649 ?

**Pull request merged**
