### PR TITLE
Make script template types customizable

### PR DESCRIPTION
**Pull request by rpoddighe**
This adds the variable `web-mode-script-template-types` that allows you to define which types of `<script>` blocks should be interpreted as HTML. I've moved the ones that were already present in `#'web-mode-scan-elements` to the default value.

### CODE REVIEW

**Comment by rpoddighe** [comment]
Sorry for all the extra commits, elisp isn't my native language 😄

**Comment by rpoddighe** [comment]
@fxbois Any chance this could be merged into the main branch at some point?

**Comment by fxbois** [comment]
@rpoddighe could you check if ```seq-come``` is compatible with emacs 23.1 (I've tried to maintain the compatibility)

**Comment by rpoddighe** [comment]
It isn't, `seq.el` is available on ELPA for emacs 24.1+, and included in emacs 25.1+. This won't work if you want to be backwards compatible with emacs 23

**Comment by rpoddighe** [comment]
I'll update the PR to ensure backwards compatibility some time next week

**Comment by fxbois** [comment]
@rpoddighe yes I prefer to keep compatibility at the moment

**Comment by rpoddighe** [comment]
It should be compatible with older versions now. If `seq-some` is not available, it will fall back to the definition that I added.

**Comment by fxbois** [comment]
thx

**Pull request merged**
