### PR TITLE
go uses ` as quote for raw strings

### PR DESCRIPTION
**Pull request by it-gro**
Thx for this really really cool mode.
I'm using it to write Hugo templates which uses Go’s html/template and text/template libraries. (https://gohugo.io/templates/)
So I just added the ` for web-mode-string-face:
` raw strings https://golang.org/ref/spec#String_literals
" interpreted strings https://golang.org/ref/spec#String_literals
' runes https://golang.org/ref/spec#Rune_literals

### CODE REVIEW

**Comment by fxbois** [comment]
@it-gro strings are not handled with font-lock-keywords.
You should look aroud the line 3366

**Comment by it-gro** [comment]
OK - Thx, I reverted my local version back to original.

3366 is:
```
 ((string= web-mode-engine "go")
...
 (setq regexp "\"\\|'"))
```

Tests cases:
```
{{ $foo1 :=  "bar"  }}
{{ $foo2 :=  `bar`  }}
{{ $foo3 :=  'bar'  }}
```

with the original version we get the following text properties (via describe-char) on the bar-string:
```
"bar" and 'bar'
```
* block-token          string (widget)Top
* font-lock-face       web-mode-block-string-face

so 'bar' is shown as string - but in go template it's not ('b' would be a rune)


changing 3366 in 
```
 ((string= web-mode-engine "go")
...
 (setq regexp "\"\\|`"))
```

has the (wanted) effect that 'bar' is no longer web-mode-block-string-face.
But 
```
`bar`
```
 is not  show with web-mode-block-string-face.

**Comment by fxbois** [comment]
```(setq regexp "\"\\|'\\|`"))```

**Comment by it-gro** [comment]
Thx, I tried this one 
for 
```
`bar`
```
I get:

```
There are text properties here:
  block-side           t
```
so no string-face for this one.

And I think, that 'bar' should not be string-face (for go template) since:
1) it is not a string in go template - it's a rune (so just one char).
2) many starters in go template (me included) do not realise that 'bar' is not a valid string. It does not help, if the syntax highlight show it as a string. I confuses a lot...
 
So I would vote for:
```
(setq regexp "\"\\|`"))
```

.. but I can't make it happen ...

**Pull request closed without merging**
