### PR TITLE
svelte engine support fxbois/web-mode#1066

### PR DESCRIPTION
**Pull request by VelikiiNehochuha**
svelte (https://svelte.dev) engine support, there is linked issue https://github.com/fxbois/web-mode/issues/1066/

### CODE REVIEW

**Comment by roket1428** [comment]
Used locally and works like a charm. Good job man.

**Comment by fxbois** [comment]
thx

**Comment by roket1428** [comment]
> svelte (https://svelte.dev) engine support, there is linked issue #1066

Could you please handle the multi line attribute assigning? As in this (I use hard tabs):
```html
		<input
			id="email"
			type="text"
			placeholder="Enter your e-mail"
			bind:value|toLowercase|trim={email}
		> <!-- I mean handling this thing's indentation like that way. -->
```
It is recommended by svelte itself.

**Comment by VelikiiNehochuha** [comment]
> ```
> <input
> 			id="email"
> 			type="text"
> 			placeholder="Enter your e-mail"
> 			bind:value|toLowercase|trim={email}
> 		>
> ```

I have same behavior already. Check your setup for this.
```
(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-indent-style 2)
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-style-padding 2)
  (setq web-mode-script-padding 2)
  (setq web-mode-block-padding 2)
  (setq web-mode-part-padding 2)
)
```

Screenshot_2019-09-23_13-59-09

**Comment by VelikiiNehochuha** [comment]
> > svelte (https://svelte.dev) engine support, there is linked issue #1066
> 
> Could you please handle the multi line attribute assigning? As in this (I use hard tabs):
> 
> ```
> 		<input
> 			id="email"
> 			type="text"
> 			placeholder="Enter your e-mail"
> 			bind:value|toLowercase|trim={email}
> 		> 
> ```
> 
> It is recommended by svelte itself.

Looks like it is already works, or I am misunderstanding.
Screenshot_2019-09-23_13-59-09
Try check your config for these list of variables (if about spaces/tabs)

```
(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-indent-style 2)
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-style-padding 2)
  (setq web-mode-script-padding 2)
  (setq web-mode-block-padding 2)
  (setq web-mode-part-padding 2)
)
```

**Pull request merged**
