### PR TITLE
[[feature]] Adding Support for Artanis, Web Application Framework, Template Files

### PR DESCRIPTION
**Pull request by WammKD**
Adds support for snippets, file-extension, and code highlighting for Artanis (https://web-artanis.com/) template files (basically, Guile Scheme).

I'm not sure if the `lsp` engine is for all LISPs or specifically Common LISP but Artanis does have some particular features/syntax that's unique to it so I added a new engine for it.

The one thing I couldn't get working was the constants; seeing as the whole list is wrapped in `regexp-opt`, I would think Emacs would take good care of outfitting them to perfect regex. but the `#t` and `#f` values don't get properly highlighted, at all, by font-lock and I'm not sure why. I think it may be the pound character causing things not to work.

### CODE REVIEW

**Comment by fxbois** [comment]
@WammKD Hey, you're the first one to submit a full "engine" compatibility patch ... thank you.
I'll check this before committing

**Comment by fxbois** [comment]
could you avoid ```with-temp-buffer``` and ```condition-case``` ?

**Comment by WammKD** [comment]
Not that I know of, without sacrificing the functionality entirely.

I originally was going to try doing it via regexp. (like everything else) but, in order to determine if parentheses close properly, you need look-behind/ahead/around – which Emacs regexp. doesn't have, unfortunately.

I tried seeing if I could find an Emacs function to handle the job by feeding said function a `string` (seemed plausible for a text editor undergirded by a LISP) but the only info. I could find was `forward-sexp`; which necessitates the `with-temp-buffer`.

Plus, – to the best of my knowledge – `forward-sexp` either works or it fails: so `condition-case` to tell whether or not the parenthesis in question ever closes.

If there is an Emacs function out there that actually just takes a `string` and outputs a `t` or a `nil` based off of whether all parentheses properly close, that'd be hella easier and cleaner and was my first option but I couldn't find any such thing existing.

**Comment by WammKD** [comment]
Would you prefer that I pull the indentation functionality to avoid any use of `with-temp-buffer` and `condition-case`? While I, personally, like the indentation functionality, I could live with it gone if it meant getting color highlighting, snippets, and the ability to use Guile's comment syntax.

**Comment by fxbois** [comment]
@WammKD Yes or you change this part to look more like the rest of the code. As you want

**Comment by WammKD** [comment]
Like I said, I don't think there's a way to make it look more like the rest of the code, given Emacs's limitation with regexp. and being able to find closing parentheses. I'll remove the code snippets 'soon as I get the chance; thanks a ton!

**Comment by WammKD** [comment]
Alright; all removed: 🖒.

**Comment by fxbois** [comment]
thx

**Pull request merged**
