### PR TITLE
support for SPIP templates

### PR DESCRIPTION
**Pull request by bystrano**
Adds an engine for templates of the SPIP CMS (https://www.spip.net).

### CODE REVIEW

**Comment by vindarel** [comment]
little note: that's a lot of commits but only 66 lines cleanly changed. (maybe rebase ?)

**Comment by bystrano** [comment]
Yes, it's not that much of a change, but I thought it would be easier to figure out my intents with the full history.

Would you like me to squash all these small commits into a big one ? Would it make my pull request more likely to get merged ?

**Comment by phenix-factory** [comment]
As a SPIP user, I'd love to see this merged inside Web-mode !

**Comment by vindarel** [comment]
@bystrano personally I'd find easier if you squashed *some* commits related in scope, but I can't speak in lieu of web-mode's maintainer :)

**Comment by fxbois** [comment]
Yes please, could you simplify the commit please

**Comment by bystrano** [comment]
Voilà, I merged all the proposed changes into one commit.

**Pull request merged**
