### PR TITLE
Improve fontification for Hugo Go Templates

### PR DESCRIPTION
**Pull request by kaushalmodi**
Continuation of https://github.com/fxbois/web-mode/pull/971 .. closed that PR by mistake when I deleted that remote branch by mistake.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Here's a good example template page that use all the fontification rules from this PR: https://gist.github.com/204d65c6b0bc145dec748240d141b825

**Comment by fxbois** [comment]
@kaushalmodi I do not see why you have functions et dot-functions

**Comment by manuel-uberti** [comment]
Anything on this one? :)

**Comment by manuel-uberti** [comment]
@kaushalmodi I am still on Jekyll, TBH, but the company I work for uses Hugo for the website. :)

**Pull request closed without merging**
