### PR TITLE
Mako files improvement

### PR DESCRIPTION
**Pull request by Randomneo**
Improved block detection for nested `{}` `${function(test={'a': 'a'})}`

Improved python indentation added keywords `try`, `except`. Fixed `pass` indentation. Added indentation for multiline dicts in mako:
    
    <%
    test = {
        'key': value
    }
    %>

### CODE REVIEW

**Comment by fxbois** [comment]
@Randomneo prev-line is already whitespace stripped

**Comment by Randomneo** [comment]
I added before cond those lines:

      (message "%s" prev-line)
      (message "%s" line)

My file
    
    <%
    test = {
        }
        test<- here cursor
    %>

output:

    ----
        }
    test
    ----

**Comment by Randomneo** [comment]
@fxbois, do I need to fix prev-line to be whitespace stripped? Any way as we can see there is no harm to leave check for whitespace.

**Comment by Randomneo** [comment]
@fxbois, Hello, please, can you provide some explanation. Why this issue was closed? It is fixed now?

**Comment by fxbois** [comment]
@Randomneo I do not really remember ... I think it is fixed now

**Pull request closed without merging**
