### PR TITLE
Fix byte-compiler warnings

### PR DESCRIPTION
**Pull request by snogge**
This should fix most of the byte-compiler warnings shown when installing this package on Emacs 29 with native compilation enabled.

### CODE REVIEW

**Comment by fxbois** [comment]
Hi @snogge 
thank you for this work.
Is it compatible with emacs 28 ?

**Comment by snogge** [comment]
No, it is not :)  I checked all my changes against the docstrings but plist-get was not marked as modified in Emacs 29.  I'll update the pull request in a little while.

What Emacs versions do you aim to support? The file says
```emacs-lisp
;; Package-Requires: ((emacs "23.1"))
```
so that was what I was assuming.

**Comment by snogge** [comment]
I've dropped the plist-get commit, the rest works on Emacs 28 as far as I can tell.

**Comment by fxbois** [comment]
@snogge if it is possible it would be great to maintain compatibility with emacs >= 23.1

**Comment by snogge** [comment]
I checked as far back as 23.4, I was not able to build 23.1 on my system.
Tests were done with the github actions defined here: https://github.com/fxbois/web-mode/commit/8c744c8c43e7a1a51800a36ceaad6a509b978449  feel free to use them if you want.

**Comment by snogge** [comment]
Actually, considering the byte-compiler warnings in https://github.com/snogge/web-mode/actions/runs/4075044915/jobs/7020929825 I'm not sure 23.4 works correctly even before my changes.

**Comment by fxbois** [comment]
Thank you for this.

**Pull request merged**
